#!usr/bin/python3
def positive_integer():
    try:
        n = int(input("Enter a positive number:"))
        if n > 0:
            return n
        else:
            print("Error: The number must be positive")
    except ValueError:
        print("Error invalid input")
get_positive_integer = positive_integer()
print(f"You entered a positive integer:{positive_integer()}")
