#!usr/bin/python3
from collections import deque
queue =deque()
queue.append('First')
queue.append('Second')
queue.append('Third')
First_item = queue.popleft()
print("First item removed":First_item)
#Output : 'First'
